apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-tasas
  namespace: grupo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-tasas
  template:
    metadata:
      labels:
        app: postgres-tasas
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: tasas
            - name: POSTGRES_USER
              value: atc
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: atc-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "atc", "-d", "tasas"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-tasas-pvc
        - name: init
          configMap:
            name: postgres-tasas-init
