{
 "title": "ATC - Controlador de Trafico Aereo",
 "tags": [ "atc" ],
 "panels": [
  {
   "title": "Logs de Vuelos",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"vuelos\"}"
    }
   ]
  },
  {
   "title": "Logs de Pistas",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"pistas\"}"
    }
   ]
  },
  {
   "title": "Logs de Tasas",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{container=\"tasas\"}"
    }
   ]
  },
  {
   "title": "Todos los logs ATC",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=~\"grupo1-qa|grupo1-prod\"}"
    }
   ]
  }
 ]
}